[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/codahale/hdrhistogram"
  revision = "3a0bb77429bd3a61596f5e8a3172445844342120"
